Lesson6
DmitrTRC/LevelUp-Hometasks pull request #4
Opened 2023-02-26 09:31 UTC by DmitrTRC

### Lesson 6

## SQL Scrips: Completed

2023-02-26 15:16 UTC, avchirkin requested changes
Добавить FK, причесать структуру таблиц

2023-02-26 15:16 UTC, avchirkin commented on Lesson6/Scripts/Clients.sql
> +	[Phone] [nchar](10) NOT NULL,
Размер маловат для телефона, могут быть длинные коды стран

2023-02-26 15:16 UTC, avchirkin commented on Lesson6/Scripts/OrderDetails.sql
> +EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Order rows information' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OrderDetails'
Нужен Foreign Key на таблицу Orders

2023-02-26 15:16 UTC, avchirkin commented on Lesson6/Scripts/Orders.sql
> +	[OrderStatusId] [uniqueidentifier] NOT NULL,
В таблице статусов это int. Это бы, кстати, выявилось, если бы ты сразу добавил FK на таблицу OrderStatuses

2023-02-26 15:16 UTC, avchirkin commented on Lesson6/Scripts/Prices.sql
> +	[ShopItemId] [uniqueidentifier] NOT NULL,
Нужен Foreign Key на таблицу ShopItem

2023-02-26 15:16 UTC, avchirkin commented on Lesson6/Scripts/Shipments.sql
> +	[Amoumt] [int] NOT NULL,
Очепятка

2023-02-26 15:16 UTC, avchirkin commented on Lesson6/Scripts/Shipments.sql
> +CREATE TABLE [dbo].[Shipments](
Нет FK на таблицу Stocks

2023-02-26 15:16 UTC, avchirkin commented on Lesson6/Scripts/ShopItem.sql
> +	[CategoryId] [uniqueidentifier] NOT NULL,
FK

2023-02-26 15:16 UTC, avchirkin commented on Lesson6/Scripts/StockKeepingUnits.sql
> +	[StockId] [uniqueidentifier] NOT NULL,
FK

2023-02-26 15:16 UTC, avchirkin commented on Lesson6/Scripts/Stocks.sql
> + CONSTRAINT [PK_NewTable] PRIMARY KEY CLUSTERED
Название лучше дать более осмысленное

2023-03-05 06:25 UTC, DmitrTRC commented on Lesson6/Scripts/Stocks.sql
> + CONSTRAINT [PK_NewTable] PRIMARY KEY CLUSTERED
Fixed.
Waiting for review

2023-03-05 06:26 UTC, DmitrTRC commented
Waiting for review on Lesson 6, 7

2023-03-08 19:03 UTC, avchirkin approved these changes

2023-03-09 13:46 UTC, merged