Lesson7
DmitrTRC/LevelUp-Hometasks pull request #5
Opened 2023-03-04 21:42 UTC by DmitrTRC

### Lesson 7 (2 Tasks )

2023-03-08 19:01 UTC, avchirkin requested changes
Небольшие замечания

2023-03-08 19:01 UTC, avchirkin commented on Lesson7/FileConcatenation/Program.cs
> +static async void FileConcat(string path)
async Task. Никогда не используй async void: https://habr.com/ru/company/otus/blog/488082/

2023-03-08 19:01 UTC, avchirkin commented on Lesson7/FileConcatenation/Program.cs
> +        string? s = "";
string.Empty

2023-03-08 19:01 UTC, avchirkin commented on Lesson7/FileConcatenation/Program.cs
> +    await using StreamWriter sw = File.CreateText("result.txt");
Сохранится в ту же директорию, где лежат бинари твоего приложения

2023-03-08 19:01 UTC, avchirkin commented on Lesson7/FileConcatenation/Program.cs
> +        while ((s = await sr.ReadLineAsync()) != null)
Как более низкоуровневая альтернатива, можно считать в буфер через FileStream. Так тоже ок, но у разных вариантов свои плюсы и минусы

2023-03-08 19:01 UTC, avchirkin commented on Lesson7/GetRoots/Program.cs
> +void PrintRootsRange(int min, int max)
Что будет, если пользователь введёт отрицательные числа? Надо бы этот кейс отработать как-то явно.
Плюс - опционально - можно "прощать" пользователя, если он ввёл диапазон задом наперёд, приняв меньшее число за начало диапазона, а большее - за конец

2023-03-09 13:45 UTC, DmitrTRC commented on Lesson7/GetRoots/Program.cs
> +void PrintRootsRange(int min, int max)
А это в техзадании не оговорено явно. Может эту логику кто вызывает делает... "M and N – arguments what can be passed by the user"  :) 

Сделаю конечно!

2023-03-10 19:48 UTC, DmitrTRC commented on Lesson7/FileConcatenation/Program.cs
> +        string? s = "";
Done

2023-03-10 19:48 UTC, DmitrTRC commented on Lesson7/FileConcatenation/Program.cs
> +        while ((s = await sr.ReadLineAsync()) != null)
Done

2023-03-10 19:48 UTC, DmitrTRC commented on Lesson7/FileConcatenation/Program.cs
> +    await using StreamWriter sw = File.CreateText("result.txt");
Done

2023-03-10 19:48 UTC, DmitrTRC commented on Lesson7/GetRoots/Program.cs
> +void PrintRootsRange(int min, int max)
Done

2023-03-10 19:52 UTC, DmitrTRC commented
### Waiting for review

2023-03-12 19:46 UTC, avchirkin approved these changes

2023-03-13 11:56 UTC, merged